global:
  scrape_interval: 30s
  external_labels:
    cluster: hcm
    replica: 0

remote_write:
  - url: "http://thanos-receive-2:10903/api/v1/receive"
    remote_timeout: 5s
    queue_config:
      batch_send_deadline: 5s
      capacity: 1000
      min_backoff: 50ms
      max_backoff: 500ms
      max_samples_per_send: 100
      min_shards: 24
      max_shards: 100

scrape_configs:
  - job_name: 'prometheus2'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9190']

  - job_name: 'receive'
    static_configs:
      - targets: ['thanos-receive-0:10702', 'thanos-receive-1:10802', 'thanos-receive-2:10902']

  - job_name: 'store'
    static_configs:
      - targets: ['thanos-store:10102']

  - job_name: 'query'
    static_configs:
      - targets: ['thanos-query:10909']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['nodeexporter:9100'] 
